apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: result-app
         imagePullPolicy: Never
         image: "vote/result-app"
         ports:
           - containerPort: 80
           