apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-app
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
       - name: vote-app
         imagePullPolicy: Never
         image: "vote/vote-app"
         ports:
           - containerPort: 80
           